#!/bin/bash
#
# fastcgi-php   Start/stop fastcgi php processes
#
# chkconfig: 2345  99 50
# description: spawn php fastcgi module
# processname: fastcgi-php

PROVIDES=/usr/bin/php-cgi
LIGHTTPD_FCGI=/usr/bin/spawn-fcgi
SERVER_IP=127.0.0.1
SERVER_PORT=9000
SERVER_USER=nobody
SERVER_GROUP=nobody
SERVER_SPAWN=8
SERVER_CHILDS=3
PHP_CGI=/usr/bin/php-cgi
PGREP=/bin/pgrep
KILLALL=/usr/bin/killall
### No editing below ####
cmd=$1

pcgi_start(){
    echo "Starting $PROVIDES..."
    $LIGHTTPD_FCGI -a $SERVER_IP -p $SERVER_PORT -u $SERVER_USER -g $SERVER_GROUP -C $SERVER_SPAWN -F $SERVER_CHILDS -f $PHP_CGI
}

pcgi_stop(){
    echo "Killing $PROVIDES..."
    $KILLALL $PROVIDES
}

pcgi_restart(){
    pcgi_stop
    sleep 2
    pcgi_start
}

pcgi_status(){
        $PGREP $PROVIDES > /dev/null
    [ $? -eq 0  ] && echo "$PROVIDES running" || echo "$PROVIDES NOT running" 

}

pcgi_help(){
    echo "Usage: $0 {start|stop|restart|status}"
}

case ${cmd} in
start) pcgi_start;;
stop) pcgi_stop;;
restart) pcgi_restart;;
status) pcgi_status ;;
*)      pcgi_help ;;
esac
